### ISSUE TITLE
Add documentation on Django

### ISSUE THREAD

**Issue by animenon** [animenon/Learning-Django#10]
What is Django and Why is it used?

**Beginners may refer** - https://github.com/animenon/Learning-Django/blob/django_examples/CONTRIBUTING.md 

This one is for Beginners.

**Comment by kapil-goyal** [comment]
Hey! I want to contribute.
Is this issue still open?

**Comment by animenon** [comment]
@kapil-goyal yes, feel free to Docs and examples of Django.

**Comment by MagdaZawora** [comment]
Hi @animenon! still looking for help?

**Comment by animenon** [comment]
@MagdaZawora feel free to add docs and examples which will help a newbie in Django.

**Comment by mraza007** [comment]
Hi is anyone still working on this issue

**Comment by animenon** [comment]
@mraza007 feel free to work on it.

**Comment by mattppal-old** [comment]
Still need help?

**Comment by animenon** [comment]
Yes @mattppal , you may make changes and raise a PR. Thanks.

**Comment by arjunvkurup** [comment]
Can I work on this?

**Comment by animenon** [comment]
@arjunvijayanathakurup sure, do add examples and docs.

**Comment by yash2189** [comment]
Can I work on adding a simple django project example?

**Comment by animenon** [comment]
Sure @yash2189

**Comment by devarshigoswami** [comment]
I've been working on django for a while now, can I work on this?

**Comment by animenon** [comment]
Sure @devarshigoswami , feel free to contribute raise PRs and issues.

**Comment by JChrisWolfe** [comment]
*Greetings!* It's March 2020, are you still willing to accept contributions?

**Comment by animenon** [comment]
Yes, @JChrisWolfe contributions are welcome.

**Comment by JChrisWolfe** [comment]
Thank you for your response, and thank you kindly.

**Comment by JChrisWolfe** [comment]
@animenon I've sent a pull request, I forgot to mention in the message of the Pull Request that in .gitignore I've added to it:

```
# Environments
Learning-Django-Env/
```

and

```
#IDE
.vscode/
```
Thank you, and welcome feedback!

**Comment by Preetham-Reddy-007** [comment]
Hey! I would like to contribute

**Comment by animenon** [comment]
@1hitman go ahead and take a hit :)

**Comment by memoisaaclo** [comment]
Hi! Can I contribute?

**Comment by animenon** [comment]
Sure @memoisaaclo Do look at the existing doc and improve it.

**Comment by pratheekcr** [comment]
Still looking for help?

**Comment by Preetham-Reddy-007** [comment]
I'm really for not able to add documentation on Django. Have been really
busy with college.
I won't be able to get it done.

**Comment by animenon** [comment]
@1hitman no issues, Feel free to contribute when you are free.
