### ISSUE TITLE
Create Django examples

### ISSUE THREAD

**Issue by animenon** [animenon/Learning-Django#3]
Feel free to create PRs with simple Django examples.

**Beginners may refer** - https://github.com/animenon/Learning-Django/blob/django_examples/CONTRIBUTING.md

**Comment by V-V-K** [comment]
I'll give it a try.

**Comment by animenon** [comment]
@V-V-K feel free to fork and add examples.

**Do read though** - https://github.com/animenon/Learning-Django/blob/django_examples/CONTRIBUTING.md

**Comment by V-V-K** [comment]
I have created the Django-powered page.
How do I add it?
Please help, I am a beginnner.

**Comment by animenon** [comment]
[First fork this repo,](https://help.github.com/articles/fork-a-repo/) (button on the right top side) then add/modify the pages you like and finally [raise a Pull request](https://help.github.com/articles/creating-a-pull-request/) (button shows up on the nav-bar once you have saved changes to your forked repo).
That's in short. But do go through https://try.github.io for a better understanding.
