### ISSUE TITLE
How to create a Django App?

### ISSUE THREAD

**Issue by animenon** [animenon/Learning-Django#5]
Add an example for "How to create a Django App?"

**Do read through for beginner steps** - https://github.com/animenon/Learning-Django/blob/django_examples/CONTRIBUTING.md

**Comment by kurianbenoy** [comment]
python3 manage.py createapp APPNAME

**Comment by animenon** [comment]
@kurianbenoy Yes that is the `createapp` command. Do add an example app and raise a PR.

**Comment by ooigavin** [comment]
Hi would you still like someone to work on this?

**Comment by animenon** [comment]
@ooigavin sure, feel free to take it up and raise a PR.

**Comment by ooigavin** [comment]
would you like the actual code for a project or just a .md file with instructions?

**Comment by animenon** [comment]
@ooigavin Sure, all welcome.
